version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      TERM: xterm-256color
    ports: 
      - "5432:5432"
    volumes:
      - ./data:/nibrs/
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
