# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - ./data:/var/local/data
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    restart: always
    environment:
      # POSTGRES_DB: nibrs_data
      PGDATA: /var/local/data
      POSTGRES_PASSWORD: example
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # 
  # sudo chown -R ubuntu:ubuntu  data
  # data/STATES/LA